
package com.nyshex.servcon.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SERVCONWebServiceSoap", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SERVCONWebServiceSoap {


    /**
     * 
     * @param fileName
     * @param orgNum
     * @param effDate
     * @param fileData
     * @param amdNum
     * @param conNum
     * @param userName
     * @return
     *     returns com.nyshex.servcon.service.ServiceContractFiling
     */
    @WebMethod(operationName = "FileContract", action = "http://www.fmc.gov/ServconWebServices/FileContract")
    @WebResult(name = "FileContractResult", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
    @RequestWrapper(localName = "FileContract", targetNamespace = "http://www.fmc.gov/ServconWebServices/", className = "com.nyshex.servcon.service.FileContract")
    @ResponseWrapper(localName = "FileContractResponse", targetNamespace = "http://www.fmc.gov/ServconWebServices/", className = "com.nyshex.servcon.service.FileContractResponse")
    public ServiceContractFiling fileContract(
        @WebParam(name = "FileData", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        byte[] fileData,
        @WebParam(name = "FileName", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String fileName,
        @WebParam(name = "OrgNum", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String orgNum,
        @WebParam(name = "ConNum", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String conNum,
        @WebParam(name = "AmdNum", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String amdNum,
        @WebParam(name = "EffDate", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String effDate,
        @WebParam(name = "UserName", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String userName);

    /**
     * 
     * @param fileName
     * @param comments
     * @param oldConNum
     * @param oldOrgNum
     * @param fileData
     * @param amdNum
     * @param newOrgNum
     * @param changeFlag
     * @param newConNum
     * @param userName
     * @return
     *     returns com.nyshex.servcon.service.ServiceContractFiling
     */
    @WebMethod(operationName = "FileCorrectedCopy", action = "http://www.fmc.gov/ServconWebServices/FileCorrectedCopy")
    @WebResult(name = "FileCorrectedCopyResult", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
    @RequestWrapper(localName = "FileCorrectedCopy", targetNamespace = "http://www.fmc.gov/ServconWebServices/", className = "com.nyshex.servcon.service.FileCorrectedCopy")
    @ResponseWrapper(localName = "FileCorrectedCopyResponse", targetNamespace = "http://www.fmc.gov/ServconWebServices/", className = "com.nyshex.servcon.service.FileCorrectedCopyResponse")
    public ServiceContractFiling fileCorrectedCopy(
        @WebParam(name = "FileData", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        byte[] fileData,
        @WebParam(name = "FileName", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String fileName,
        @WebParam(name = "oldOrgNum", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String oldOrgNum,
        @WebParam(name = "oldConNum", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String oldConNum,
        @WebParam(name = "newOrgNum", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String newOrgNum,
        @WebParam(name = "newConNum", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String newConNum,
        @WebParam(name = "changeFlag", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String changeFlag,
        @WebParam(name = "AmdNum", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String amdNum,
        @WebParam(name = "UserName", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String userName,
        @WebParam(name = "Comments", targetNamespace = "http://www.fmc.gov/ServconWebServices/")
        String comments);

}
